# Permalinks
permalink: pretty

# Setup
title: angst bij kinderen
tagline:
url: https://angstbijkinderen.nl
paginate: 1
baseurl: ""
analytics_id: UA-72478077-1

defaults:
- scope:
    path: "_projects*/"
  values:
    collection_basename: projects
- scope:
    path: "_staff_members*/"
  values:
    collection_basename: staff_members        
- scope:
    path: "_news*/"
  values:
    collection_basename: news      
- scope:
    path: "*_en/"
  values:
    locale: en
    lang: en-US
    collection_suffix: _en
- scope:
    path: "*_de/"
  values:
    locale: de
    lang: de-DE
    collection_suffix: _de    
- scope:
    path: ""
  values:
    locale: default
    lang: nl-NL    
- scope:
    path: "_pages_en/index.*"
  values:
    permalink: "/en/"    
- scope:
    path: "_pages_de/index.*"
  values:
    permalink: "/de/"      

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: :compressed

# About/contact
author:
  name: Anke Klein
  url: http://ankeklein.nl
  email: kas@fsw.leidenuniv.nl

locales:
  default:
    baseurl: ""
    name: Dutch
    lang: nl-NL
  en:
    baseurl: /en
    name: English
    lang: en-US    
  de:
    baseurl: /de
    name: Deutsch
    lang: de-DE        

collections:
  pages_en:
    output: true
    permalink: /en/:path/  
  pages_de:
    output: true
    permalink: /de/:path/      
  staff_members:
    output: true
    permalink: /team/:path/      
  staff_members_en:
    output: true    
    permalink: /en/team/:path/  
  staff_members_de:
    output: true    
    permalink: /de/team/:path/      
  projects:
    output: true
    permalink: /projects/:path/
  projects_en:
    output: true
    permalink: /en/projects/:path/
  projects_de:
    output: true
    permalink: /de/projects/:path/
  news:
    output: true
    permalink: /news/:path/
  news_en:
    output: true
    permalink: /en/news/:path/    
  info:
    output: true  
  blog:
    output: true  

# Custom vars
version: 2.0.0
github:
  repo: https://github.com/ankeklein

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
